Enhance Build Process
HSLdevcom/OpenTripPlanner-data-container pull request #428
Opened 2024-12-19 05:42 UTC by laardee

This PR introduces some improvements and optimizations:

* Splits Gulp runtime configurations into router-specific files for better modularity.
* Updates Dockerfiles, light-http configs, and scripts to use parameters, avoiding unnecessary changes to git-tracked files.
* Improves the clarity of error messages in specific scenarios.
* Adds support for environment variables to skip selected build steps, reducing development time.
* Skips pushing images to the Docker registry if credentials are not defined, ensuring the build process in unconfigured environments, like development.

2024-12-23 13:16 UTC, vesameskanen requested changes
Thank you for the contribution. Using variables instead of modifying local  version managed files is a good improvement. 

Some notes, though:

- Unused task/PatchDeploymentFiles.js should be deleted, the reference to it in gulpfile removed and  README.md updated to reflect the changes.

- Build process works but creates a broken OTP image.  When running the image,  kubernetes deployment shows an error:

    Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/otp/entrypoint.sh": stat /var/otp/entrypoint.sh: no such file or directory: unknown

2024-12-23 13:16 UTC, vesameskanen commented on task/Common.js
> +
Would it be more natural to import this one liner from util.js ? task folder contains gulp tasks and the main update logic.

2024-12-23 13:37 UTC, vesameskanen commented
Found out that our container deployment mounts data storage to path  `/var/otp` .  I assume that this mounting overwrites the original folder where the entrypoint script is.

2024-12-27 10:11 UTC, laardee commented on task/Common.js
> +
True, moved that to util.js

2024-12-27 10:24 UTC, laardee commented
> Found out that our container deployment mounts data storage to path `/var/otp` . I assume that this mounting overwrites the original folder where the entrypoint script is.

The entrypoint.sh is now in the parent `/var/` directory.

Are these mounts and other cluster-related variables documented somewhere? I briefly tried to find those without success.

2024-12-27 11:10 UTC, vesameskanen commented
Opentripplanner-data-container, opentripplanner and their deployment configurations are indeed a complex system. It is hard to figure out how the actual runtime environment and configurations found from it get assembled, because the logic is split into many repositories.

The mentioned conflicting mount path is defined here:
https://github.com/HSLdevcom/digitransit-kubernetes-deploy/blob/master/roles/aks-apply/files/dev/opentripplanner-hsl-v2-dev.yml#L58

Environment variables for the data loader can be found here:
https://github.com/HSLdevcom/digitransit-kubernetes-deploy/blob/master/roles/aks-apply/files/dev/otp-data-builder-hsl-v3-dev.yml

These deployments are for HSL routing in development environment.

2024-12-27 15:20 UTC, vesameskanen approved these changes
Seems to work now.  I will ask second opinion from my colleague Joel before merging.

2024-12-30 09:37 UTC, merged